"""
AI Citation:
Cursor Auto was used to generate the code.

Prompt: "In Matts Workspace, I want a super simple, minimal code AAC board interface 
that has buttons that have images from the @arasaac_synset_mapping_20251106_130530.csv, 
the buttons are generated by passing the board a list of synset IDs"

AI Assistant (Cursor Auto): Created the complete AACBoard class implementation including:
- CSV loading and synset-to-image mapping functionality
- Tkinter GUI with scrollable grid layout
- Image loading from ARASAAC API URLs via requests and PIL
- Button generation with images and keyword labels
- Click event handling with terminal logging
- Example usage with sample synset IDs

The implementation provides a minimal, functional AAC communication board interface
that dynamically generates buttons from synset IDs mapped to pictogram images.
"""

import tkinter as tk
from tkinter import ttk
import pandas as pd
from PIL import Image, ImageTk
import requests
from io import BytesIO


class AACBoard:
    def __init__(self, csv_path, synset_ids):
        """
        Initialize the AAC board interface.
        
        Args:
            csv_path: Path to the arasaac_synset_mapping CSV file
            synset_ids: List of synset IDs to display as buttons
        """
        self.synset_ids = synset_ids
        
        # Load CSV and create mapping
        df = pd.read_csv(csv_path)
        # Get first occurrence of each synset (or filter by provided synset_ids)
        self.synset_map = {}
        for synset in synset_ids:
            matches = df[df['synset'] == synset]
            if not matches.empty:
                row = matches.iloc[0]
                self.synset_map[synset] = {
                    'image_url': row['image_url'],
                    'keyword': row['primary_keyword'],
                    'pictogram_id': row['pictogram_id']
                }
        
        # Create main window
        self.root = tk.Tk()
        self.root.title("AAC Board")
        self.root.geometry("800x600")
        
        # Create main frame
        main_frame = ttk.Frame(self.root, padding="10")
        main_frame.grid(row=0, column=0, sticky=(tk.W, tk.E, tk.N, tk.S))
        
        # Configure grid weights
        self.root.columnconfigure(0, weight=1)
        self.root.rowconfigure(0, weight=1)
        main_frame.columnconfigure(0, weight=1)
        main_frame.rowconfigure(0, weight=1)
        
        # Create canvas with scrollbar
        canvas = tk.Canvas(main_frame)
        scrollbar = ttk.Scrollbar(main_frame, orient="vertical", command=canvas.yview)
        scrollable_frame = ttk.Frame(canvas)
        
        scrollable_frame.bind(
            "<Configure>",
            lambda e: canvas.configure(scrollregion=canvas.bbox("all"))
        )
        
        canvas.create_window((0, 0), window=scrollable_frame, anchor="nw")
        canvas.configure(yscrollcommand=scrollbar.set)
        
        # Load and display buttons
        self.buttons = []
        self.load_buttons(scrollable_frame)
        
        canvas.grid(row=0, column=0, sticky=(tk.W, tk.E, tk.N, tk.S))
        scrollbar.grid(row=0, column=1, sticky=(tk.N, tk.S))
        main_frame.rowconfigure(0, weight=1)
        main_frame.columnconfigure(0, weight=1)
        
        # Bind mousewheel to canvas
        def on_mousewheel(event):
            canvas.yview_scroll(int(-1*(event.delta/120)), "units")
        canvas.bind_all("<MouseWheel>", on_mousewheel)
    
    def load_image_from_url(self, url):
        """Load image from URL and resize for button."""
        try:
            response = requests.get(url, timeout=5)
            img = Image.open(BytesIO(response.content))
            img = img.resize((100, 100), Image.Resampling.LANCZOS)
            return ImageTk.PhotoImage(img)
        except Exception as e:
            print(f"Error loading image from {url}: {e}")
            # Return a placeholder
            img = Image.new('RGB', (100, 100), color='gray')
            return ImageTk.PhotoImage(img)
    
    def load_buttons(self, parent):
        """Load and display buttons for each synset."""
        row = 0
        col = 0
        cols_per_row = 4
        
        for synset_id in self.synset_ids:
            if synset_id not in self.synset_map:
                print(f"Warning: Synset {synset_id} not found in CSV")
                continue
            
            info = self.synset_map[synset_id]
            
            # Create button frame
            btn_frame = ttk.Frame(parent, padding="5")
            btn_frame.grid(row=row, column=col, padx=5, pady=5)
            
            # Load image
            photo = self.load_image_from_url(info['image_url'])
            
            # Create button
            btn = tk.Button(
                btn_frame,
                image=photo,
                text=info['keyword'],
                compound=tk.TOP,
                width=120,
                height=130,
                command=lambda s=synset_id: self.on_button_click(s)
            )
            btn.image = photo  # Keep a reference
            btn.pack()
            
            self.buttons.append(btn)
            
            # Update grid position
            col += 1
            if col >= cols_per_row:
                col = 0
                row += 1
    
    def on_button_click(self, synset_id):
        """Handle button click."""
        info = self.synset_map.get(synset_id, {})
        keyword = info.get('keyword', synset_id)
        print(f"Clicked: {keyword} ({synset_id})")
        # You can extend this to handle speech synthesis, etc.
    
    def run(self):
        """Start the GUI."""
        self.root.mainloop()


if __name__ == "__main__":
    # Example usage
    csv_path = "../Kaitlin's Workspace/arasaac_synset_mapping_20251106_130530.csv"
    
    # Example synset IDs
    synset_ids = [
        "04222469-n",  # pavement
        "07951744-n",  # water
        "04125115-n",  # carpet
        "03944520-n",  # pillow
        "02703861-n",  # ambulance
        "04099721-n",  # ring
    ]
    
    board = AACBoard(csv_path, synset_ids)
    board.run()
